# Generated by Django 3.2.3 on 2021-05-27 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cycle_app', '0002_institute_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='versity_life_cycle',
            name='institute',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cycle_app.institute_info'),
        ),
    ]
