# Generated by Django 3.2.3 on 2021-05-27 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cycle_app', '0003_versity_life_cycle_institute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='versity_life_cycle',
            name='institute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cycle_app.institute_info'),
        ),
    ]
