# Generated by Django 3.2.3 on 2021-05-27 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cycle_app', '0004_alter_versity_life_cycle_institute'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='versity_life_cycle',
            name='dept',
        ),
        migrations.RemoveField(
            model_name='versity_life_cycle',
            name='session',
        ),
    ]
