# Generated by Django 3.2.3 on 2021-05-27 21:41

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cycle_app', '0006_alter_institute_info_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='versity_life_cycle',
            name='event',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
