# Generated by Django 2.2 on 2021-05-28 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycle_app', '0007_alter_versity_life_cycle_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='institute_info',
            name='public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='versity_life_cycle',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
